---
layout: post
title: Varietas Vanili Tahan Penyakit
date: '2019-05-20T18:08:00.000+07:00'
author: Yudi Anto
tags:
- Perkebunan
- vanili
modified_time: '2022-12-17T19:10:22.328+07:00'
thumbnail: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgk_FIcdMaJNg1ItZY9tp4vnNjSO7KtzfUCNl1teASpSEDKSednbi2eFs_u0dnXDqgYTmT46myAzc6WIBgiyahB2ku0t_z6DD8LC3y3pqadObI8h5F0maiRyOSgGff81uOEAnHt4oMYG96tuvYXQtU85LzExzLdYjwXLCefE_4uWUutB10gWxIvAnDPUw/s72-c/vanili-3-1.jpg
blogger_id: tag:blogger.com,1999:blog-3092549465158545190.post-8795704501700675157
blogger_orig_url: https://www.budidayatani.com/2019/05/varieteas-vanili-tahan-penyakit.html
---

<p>Varietas vanili tahan penyakit adalah varietas vanili yang dapat bertahan terhadap penyakit dan serangan hama, sehingga diperlukan sedikit pestisida untuk melindunginya. Varietas ini telah berhasil dikembangkan melalui berbagai kombinasi genetik dan teknologi modern, sehingga mampu bertahan dari penyakit tanpa banyak bantuan dari pestisida. Hasilnya adalah vanili berkualitas tinggi dengan rasa yang lebih kuat dan aroma yang lebih dalam. Varietas ini juga memiliki jenis yang berbeda sehingga dapat disesuaikan dengan berbagai jenis kondisi tanah dan iklim.</p>
<p>Musim panas 1987 di Perancis terasa lebih indah buat Bambang Hadisutrisno. Pot-pot tomat marmand Rfdan Pryang diungsikan dari rumah kaca tumbuh subur dan menghasilkan buah. Padahal 2 varietas itu dikenal rentan fusarium penyebab busuk batang yang mematikan. Tomat kebal cendawan setelah &ldquo;disusupi&rdquo; bibit penyakit yang sudah dilemahkan.</p>
<p>Menemukan benteng penahan serbuan fusarium obsesi Bambang jauh sebelum menjejakkan kaki di Perancis pada 1983. Sudah lama hatinya teriris melihat ratusan hektar vanili di sentra-sentra tanah air luluh-lantak diterjang busuk batang karena Fusarium oxysporum.</p>
<p>Kengototan pria kelahiran Wonosobo 56 tahun silam itu menuntut ilmu mengatasi BBP begitu busuk batang panili disebut sungguh beralasan. Sejak bocah belasan tahun, vanili sudah menjadi bagian hidup. Bermodal menjual 3 ayam peliharaan Bambang yang baru ujian akhir sekolah dasar menanam anggota famili Orchidaceae itu.</p>
<p>Memasuki masa kuliah pada 1970-an, bidang Epidemiologi Penyakit Tanaman di Fakultas Pertanian Universitas Gadjah Mada jadi pilihan. Kala itu momok BBP merajalela di seluruh sentra. Beragam cara mengatasi hanya menuai kegagalan. &ldquo;Diatasi dengan pestisida hasilnya nol.</p>
<p>Perlakuan pemupukan berimbang, sama saja,&rdquo; tutur ayah 2 putra itu. Tekad membawa pulang teknologi menghasilkan vanili tahan BBP ia bawa terbang ke Perancis.</p>
<p>Definisi Varietas Vanili Tahan Penyakit, Tinjauan Penggunaan dan Manfaatnya.</p>
<p>Varietas Vanili Tahan Penyakit adalah varietas vanili yang tahan terhadap penyakit yang umumnya menyerang tanaman vanili. Ini memiliki beberapa manfaat, termasuk tingkat produksi yang lebih tinggi, lebih sedikit penyakit, dan umur panjang tanaman. Varietas ini juga cocok untuk perkebunan skala kecil karena lebih mudah dikelola. Manfaat lainnya termasuk rasa vanili yang lebih kuat dan lebih banyak produk yang dihasilkan dari tanaman. Varietas Vanili Tahan Penyakit juga memiliki kemampuan yang lebih baik untuk menahan perubahan iklim dan membantu mengurangi biaya produksi.</p>
<div class="separator" style="clear: both;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgk_FIcdMaJNg1ItZY9tp4vnNjSO7KtzfUCNl1teASpSEDKSednbi2eFs_u0dnXDqgYTmT46myAzc6WIBgiyahB2ku0t_z6DD8LC3y3pqadObI8h5F0maiRyOSgGff81uOEAnHt4oMYG96tuvYXQtU85LzExzLdYjwXLCefE_4uWUutB10gWxIvAnDPUw/s1511/vanili-3-1.jpg" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="600" data-original-height="850" data-original-width="1511" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgk_FIcdMaJNg1ItZY9tp4vnNjSO7KtzfUCNl1teASpSEDKSednbi2eFs_u0dnXDqgYTmT46myAzc6WIBgiyahB2ku0t_z6DD8LC3y3pqadObI8h5F0maiRyOSgGff81uOEAnHt4oMYG96tuvYXQtU85LzExzLdYjwXLCefE_4uWUutB10gWxIvAnDPUw/s600/vanili-3-1.jpg"/></a></div>
<h2>Riset Mendalam</h2>
<p>Di ENSA de Montpellier universitas tempat Bambang menuntut ilmu selama di Perancis ide melawan penyakit dengan cendawan yang dibuat lemah mencuat. &ldquo;Intinya seperti pemberian vaksin cacar pada manusia supaya kebal,&rdquo; kata Bambang.</p>
<p>Masuknya virus cacar memaksa tubuh menghasilkan antibodi. Ketika penyebab penyakit yang sesungguhnya menyerang, tubuh siap melawan. Pada tanaman, antibodi itu ialah senyawa-senyawa fenol. Keinginan membuktikan teori itu langsung pada vanili urung dilakukan.</p>
<p>Kerabat anggrek itu tidak tumbuh di iklim subtropis. Tomat Solanum esculentum lantas jadi pilihan lantaran kerap jadi korban Fusarium sp juga. Dua varietas paling rentan, marmand Rf dan marmand Pr menjadi kelinci percobaan.</p>
<p>Bibit-bibit berumur 10 sampai 14 minggu dicelupkan ke dalam cairan berisi fusarium yang dilemahkan nantinya disebut sebagai autovaksin sebelum ditanam di rumah kaca.</p>
<p>Bila autovaksin bekerja, tanaman menjadi kebal saat sumber penyakit sesungguhnya datang. Pada percobaan pertama sebanyak 50 pot, sebagian besar dimusnahkan lantaran tak kuat menahan serangan fusarium</p>
<h3>Miselium kapas</h3>
<p>Nyaris 4 tahun berkutat di laboratorium dan rumah kaca, titik terang itu akhirnya datang juga. Di musim panas 1987, tomat-tomat hasil percobaan yang kesekian kali tumbuh subur. Untuk menguji keberhasilan di rumah kaca, tanaman diboyong ke luar. &ldquo;Ternyata tomat tetap sehat, berbunga, dan berbuah,&rdquo; ujar Bambang. Butir pertama yang dipetik dan dicicipi terasa begitu nikmat.</p>
<p>Kesuksesan di lapang itu lantas dibawa kembali ke dalam laboratorium. Dua uji dilakukan untuk meyakinkan penemuan. Jaringan tanaman dari batang dan tangkai daun di ruas pertama ditumbuhkan dalam media agar. Saat miselium mirip kapas tumbuh mendominasi, perasaan bahagia menyeruak.</p>
<p>&ldquo;Itu miselium cendawan yang dilemahkan. Artinya autovaksin bekerja menahan serbuan fusarium penyebab penyakit di dalam jaringan tanaman,&rdquo; kata mantan dekan Fakultas Pertanian UGM periode 1997 sampai 2000 itu. Bila miselium tipis-tipis yang terbentuk, fusarium &ldquo;jahat&rdquo;-lah yang menang.</p>
<h3>Penyakit Terbawa setek</h3>
<p>Uji kedua dengan elektroporisis. Cara itu untuk mengetahui perbedaan gen antara tanaman yang diberi autovaksin dengan kontrol. Perbedaan itu penting lantaran fusarium bersifat spesifik. Dua &ldquo;pita&rdquo; hasil uji elektroporesis pada tanaman mengandung autovaksi dan 7 &ldquo;pita&rdquo; pada kontrol menunjukkan perbedaan gen menjadi bukti kuat. Bagi Bambang inilah jawaban untuk momok yang membuat pekebun vanili angkat tangan.</p>
<p>Penemuan yang membawanya meraih gelar doktor itu diboyong pulang. Namun, proses adaptasi teknologi pada vanili tak mudah. Setek sehat sulit didapat, padahal jadi prasarat menghasilkan bibit tahan BBP.</p>
<p>Guru besar Epidemiologi Penyakit Tumbuhan itu pun harus memutar otak agar autovaksi bertahan dalam jaringan tanaman. Tujuannya bila tanaman disetek untuk diperbanyak, benteng pertahanan BBP itu tetap terbawa.</p>
<p>Maka lagi-lagi 6 tahun ia habiskan di laboratorium dan rumah kaca. Toh, pengorbanan itu tidak sia-sia. Kini sulur-sulur vanili tahan BBP menyebar di berbagai sentra. Di saat para kebun mulai menuai polong-polong dari tanaman sehat, senyum.bahagia tersungging di bibirnya. Ubijalar</p>
<p>Lagu senada disenandungkan Dr Mesakh Tombe. Mirip yang dilakukan Bambang Hadisutrisno, periset pada Balai Penelitian Tanaman Rempah dan Obat (Balittro) itu menantang BBP dengan bibit yang &ldquo;disusupi&rdquo; cendawan nonpatogenik.</p>
<p>Setek asal tanaman sehat dicelupkan ke dalam cairan putih mengandung parasit yang tidak menyebabkan penyakit itu. Begitu cendawan nonpatogenik menguasai jaringan tanaman, bibit kebal serangan fusarium ganas.</p>
<p>Ide menggunakan cendawan nonparasit itu mengalir deras begitu membaca jurnal-jurnal penelitian di suatu siang pada 1990. Salah satu jurnal mengungkap sukses periset di Jepang mengendalikan fusarium pada ubijalar dengan &ldquo;memvaksin&rdquo; umbi sebelum ditanam. &ldquo;Kenapa tidak diterapkan pada vanili?&rdquo; hatinya membatin. Ayah 3 anak itu kian yakin lantaran cara serupa diterapkan pada melon dan stroberi di Amerika Serikat.</p>
<p>Namun, bagaimana cara memperoleh cendawan nonpatogenik masih tanda tanya. &ldquo;Di alam banyak sekali jenis fusarium, baik yang patogen maupun nonpatogen,&rdquo; tutur Mesakh. Metoda mendapatkan parasit yang tidak menyebabkan penyakit itulah yang ia kejar kala melanjutkan studi doktoral ke Jepang. Proses itu menjadi batu pijakan sebelum mencapai tahap berikut: menginfeksi pada tanaman.</p>
<p>Berbekal ilmu dari Negara Matahari Terbit itulah Mesakh kini memproduksi bibit tahan fusarium. Februari silam, pekebun di Desa Kemetuk, Tabanan, Bali, memanen polong dari bibit asal Balittro yang ditanam pada Oktober 2001.</p>
<h4>Vanili liar</h4>
<div class="separator" style="clear: both;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjYLmM7WSCRoeS2vB3FACAJEI5TMzcmy_BKTuEisiMuE_-GYinHutVNkT-SE0ggyTLr1KJNjKZRWDPaZLZ01AI_J-JIGK0vPmiwc0rhpii9LWYVaBUil3qvBuMTQCHD33CtueSPPpl0th5GrV74_NruR5heLWvGXOi7b1XuNWMsXZpkaeae_VYwBMFydA/s320/h_800x588.jpg" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="600" data-original-height="235" data-original-width="320" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjYLmM7WSCRoeS2vB3FACAJEI5TMzcmy_BKTuEisiMuE_-GYinHutVNkT-SE0ggyTLr1KJNjKZRWDPaZLZ01AI_J-JIGK0vPmiwc0rhpii9LWYVaBUil3qvBuMTQCHD33CtueSPPpl0th5GrV74_NruR5heLWvGXOi7b1XuNWMsXZpkaeae_VYwBMFydA/s600/h_800x588.jpg"/></a></div>
<p>Yang juga bersusah-payah melawan fusarium ialah Dra Endang Hadipoentyanti, MS. Demi melawan Fendy RP musuh besar pekebun vanili periset pada Balittro itu rela berjalan kaki menembus hujan di Gunung Legon. Dari informasi yang diterima, gunung di Cianjur itu &ldquo;menyimpan&rdquo; vanili hutan yang diduga memiliki gen tahan fusarium.</p>
<p>Berbeda dengan&nbsp;&nbsp; 2 koleganya, alumnus Fakultas Biologi UGM itu memilih mengatasi BBP dengan menghasilkan varietas baru. &ldquo;Salah satu cara dengan mengawinkan vanili budidaya dengan yang liar,&rdquo; tutur Endang. Keragaman genetik jadi modal penting.</p>
<p>Maka sejak 1994 mulailah Endang dan beberapa rekan di Balittro mengumpulkan klon-klon vanili dari berbagai daerah. Tak jarang malam hari ia lewatkan di kebun-kebun petani untuk mengamati vanili liar.</p>
<p>&ldquo;Sifat vanili liar tidak sama dengan jenis budidaya. Bunga vanili liar biasanya mekar lebih lama dan harum,&rdquo; kata perempuan yang gemar melukis itu. Pengetahuan itu penting untuk menguji kompatibilitas vanili hutan dengan vanili budidaya.</p>
<p>Uji lapang Sepuluh tahun berlalu, 22 klon vanili budidaya, 7 liar, 34 semaklon, 9 hibrida, dan 4 mutan diperoleh. Dari evaluasi dan seleksi didapat 4 klon harapan yang diharapkan menjadi varietas berproduksi tinggi dan tahan BBP. Namun, peijalanan peraih master bidang pemuliaan dari UGM itu belum final.</p>
<p>Klon yang dikenal dengan nama vania 1 sampai 4 itu hingga kini masih diuji ketangguhannya di sentra-sentra penanaman di Bali, Banten, dan Jawa Barat. Pekebun boleh berharap tahun-tahun mendatang sang penantang fusarium siap ditanam</p>
<h2>Penutup</h2>
<p>Varietas Vanili Tahan Penyakit adalah jenis vanili yang dikembangkan untuk memiliki ketahanan terhadap hama dan penyakit. Ini menawarkan manfaat bagi petani karena mereka dapat mempertahankan hasil tanamannya tanpa banyak pengeluaran. Varietas ini juga menawarkan rasa vanili yang lebih kuat dan manis dibandingkan varietas tradisional. Dengan varietas Vanili Tahan Penyakit, petani dapat menghasilkan hasil yang lebih tinggi karena tidak lagi harus mengandalkan pestisida dan fungisida.</p>