---
layout: post
title: 'Rambutan zainal mahang: rambutan terbesar di dunia'
date: '2022-12-23T16:08:00.001+07:00'
author: Yudi Anto
tags:
- Rambutan
- Perkebunan
modified_time: '2022-12-23T16:08:16.458+07:00'
thumbnail: https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEisu8TSUF9_popwvqy3XXrJ-Idvp1EWscLzey3cxsMV7bdvbBZQuzGU5fHavKWtSxyzhKVtYeh82p7IdE6b6efqD9dw-4lTOjHoVcwfWA91ebAyopU16dbwmYAe2sbGv0oCwa89AODK06L-NZGnpY1uEhd9XwKr1tQ18i1YNiI7JIpMZqR4IIzs5zWV5w/s72-c/rambutan-zaenal-mahang.jpg
blogger_id: tag:blogger.com,1999:blog-3092549465158545190.post-6137542163751192679
blogger_orig_url: https://www.budidayatani.com/2022/12/rambutan-zainal-mahang-rambutan.html
---

<p>&ldquo;Mau mencicip rambutan terbesar di dunia?&rdquo; tanya Azis Widyanto SP seraya menyodorkan kantong plastik hitam berisi Nephelium lappaceum. Sebutir buah yang dicomot dari dalam plastik berukuran lebih besar daripada telur angsa, berwarna merah tua menyala.</p>
<p>Saat kulit dibuka, di dalamnya terlihat daging buah berwarna putih susu dan kering. Penampilan yang menggoda itu dibarengi rasa manis yang menyergap lidah begitu daging buah dilahap. Daging buah tebal, ngelotok, dan biji kecil. Saat mengunyah pipi menjadi menggembung seperti meniup balon saking besarnya buah.</p>
<p>Azis Widyanto, kepala Sub Laboratorium Balai Pengawasan dan Sertifikasi Benih Tanaman Pangan dan Hortikultura (BPSB-TPH), Kalimantan Selatan, menyebutnya rambutan zainal mahang.</p>
<p>Disebut begitu karena buah tanaman anggota famili Sapindaceae itu asal Desa Sungai Hanyar Mahang, Kecamatan Pandawan, Kabupaten Hulu Sungai Tengah, Kalimantan Selatan. Pemilik pohonnya H Zainal Abidin.</p>
<h2 id="Stabil">Daging buah yang sempurna</h2>
<div class="separator" style="clear: both;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEisu8TSUF9_popwvqy3XXrJ-Idvp1EWscLzey3cxsMV7bdvbBZQuzGU5fHavKWtSxyzhKVtYeh82p7IdE6b6efqD9dw-4lTOjHoVcwfWA91ebAyopU16dbwmYAe2sbGv0oCwa89AODK06L-NZGnpY1uEhd9XwKr1tQ18i1YNiI7JIpMZqR4IIzs5zWV5w/s1511/rambutan-zaenal-mahang.jpg" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="600" data-original-height="850" data-original-width="1511" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEisu8TSUF9_popwvqy3XXrJ-Idvp1EWscLzey3cxsMV7bdvbBZQuzGU5fHavKWtSxyzhKVtYeh82p7IdE6b6efqD9dw-4lTOjHoVcwfWA91ebAyopU16dbwmYAe2sbGv0oCwa89AODK06L-NZGnpY1uEhd9XwKr1tQ18i1YNiI7JIpMZqR4IIzs5zWV5w/s600/rambutan-zaenal-mahang.jpg"/></a></div>
<p>Zainal mahang pantas disebut rambutan raksasa terbaik. Selama ini julukan rambutan terbesar memang kerap ditujukan pada garuda. Varietas unggul nasional asal Sungaiandai, Kalimantan Selatan, yang dilepas 22 tahun silam Itu berkulit merah kekuningan dengan rambut merah berujung agak kuning. Ukurannya setara telur ayam ras, zaenal mahang sebesar telur angsa. Waktu ditimbang bobot rata-rata zainal mahang 73,6 g; bandingkan dengan garuda 68,15 g.</p>
<p>Menurut Dr Moh Reza Tirtawinata MS, pakar buah di Bogor, Jawa Barat, selama ini di tanahair dikenal 3 rambutan jumbo: simacan, garuda, dan arialaka. Di Kabupaten Bulungan, Kalimantan Timur, Dr Luthfi Bansir SP MP, doktor buah dari Universitas Brawijaya, Malang, menemukan rambutan jaro mas yang ukurannya sebesar telur bebek. Sayangnya karakter berbuah besar simacan, garuda, dan arialaka tidak stabil. Pada garuda kerap ditemui buah kempot alias tak berisi daging buah. Beda dengan buah zainal mahang yang 99% terisi sempurna.</p>
<p>Menurut si empunya tanaman, tetua rambutan zainal mahang berupa tanaman asal biji yang ditanam orang tuanya puluhan tahun silam. &ldquo;Buahnya besar sekali bila dibandingkan rambutan kebanyakan, tapi tidak ngelotok," kata Zainal Abidin, pensiunan Dinas Penerangan Kabupaten Hulu Sungai Tengah.</p>
<p>Biji-biji dari buah yang dipanen lalu ditanam. Salah satunya tumbuh menjadi tanaman dengan buah berdaging ngelotok. Berbekal pelajaran prakarya di era 1960-an saat belajar di sekolah menengah, Zainal mencangkok tanaman berbuah jumbo dan ngelotok itu pada 1985. Maklum melihat sosok buahnya banyak orang tertarik untuk menanam.</p>
<h2 id="bibit">Bibit rambutan unggul</h2>
<div class="separator" style="clear: both;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtoBmEKxgpbbnHOR4eD2vIMaqdxoJf8iiUirvz3tHEugSj1VOjztp_Cby-3gVpplQzt0FkTl86qf_YdytRyz9_CwnY2D8zltldzcX3zV2yzI2py456IxNUTf2NfeGiu95h7sw6J4tpqbEL4oSQVrP2ZJ0K5E94Q0d9GBTIgzd0IrHAxG_FlqTF-aiygw/s768/rambutan-zaenal-768x432.jpg" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="600" data-original-height="432" data-original-width="768" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgtoBmEKxgpbbnHOR4eD2vIMaqdxoJf8iiUirvz3tHEugSj1VOjztp_Cby-3gVpplQzt0FkTl86qf_YdytRyz9_CwnY2D8zltldzcX3zV2yzI2py456IxNUTf2NfeGiu95h7sw6J4tpqbEL4oSQVrP2ZJ0K5E94Q0d9GBTIgzd0IrHAxG_FlqTF-aiygw/s600/rambutan-zaenal-768x432.jpg"/></a></div>
<p>Orang mula-mula mengenal bibit itu dengan nama garuda-menilik sosok buah yang besar. Penyebarannya di beberapa wilayah di Kalimantan Selatan hingga ke Bandung (Jawa Barat), dan Pati (Jawa Tengah).</p>
<p>Belakangan pengamatan oleh Dinas Pertanian setempat dan Balai Pengawasan dan Sertifikasi Benih Tanaman Pangan dan Hortikultura IBPSB-TPH), Kalimantan Selatan, menunjukkan zainal mahang berbeda dengan garuda. Ketua tim peneliti, Ir Yayat Hidayat H MP menduga zainal mahang varian dari keturunan garuda.</p>
<p>Harap mafhum, di kebun Zainal juga tumbuh pohon rambutan garuda. Musim berbunga keduanya kerap berbarengan sehingga kerabat leci itu saling menyerbuk secara alami.</p>
<p>Dugaan lain zainal mahang merupakan persilangan alami rambutan warisan orang tua dengan rambutan berbuah kecil tapi ngelotok seperti si batok dan antalagi. Maksudnya, biji hasil penyerbukan bebas membentuk kombinasi genetik baru, sehingga hasilnya beragam yang tidak sama dengan induknya.</p>
<h2 id="Adaptasi">Adaptasi tinggi</h2>
<div class="separator" style="clear: both;"><a href="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhIcSmHzN60rrZFhKWU4uYtapJrX0OBPLV7Sf_s3HP2nIrQiGMMV0uAZ8gDqZVnqhayUrO0cUa4eNDzKKanYCKJMGAp6oGJqkYcPAtk0pDQTmaI0ZmDfuygjT6eJFFWc5-jHyLzXMdSqlMX22tYTliwkYOwD4wxTa1zYjL6T0HyND5-3J7lGAByJo4DdA/s768/zaenal-mahang-768x432.jpg" style="display: block; padding: 1em 0; text-align: center; "><img alt="" border="0" width="600" data-original-height="432" data-original-width="768" src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhIcSmHzN60rrZFhKWU4uYtapJrX0OBPLV7Sf_s3HP2nIrQiGMMV0uAZ8gDqZVnqhayUrO0cUa4eNDzKKanYCKJMGAp6oGJqkYcPAtk0pDQTmaI0ZmDfuygjT6eJFFWc5-jHyLzXMdSqlMX22tYTliwkYOwD4wxTa1zYjL6T0HyND5-3J7lGAByJo4DdA/s600/zaenal-mahang-768x432.jpg"/></a></div>
<p>Zainal mahang mampu tumbuh di lahan agak masam dan masam seperti tanah gambut dan latosol. Artinya daya adaptasi tanaman sangat tinggi.</p>
<p>Di kebun Zainal Abidin, pohon induk dan 24 tanaman hasil perbanyakan vegetatif tumbuh di tegalan yang kerap tergenang saat musim hujan dan kering kala kemarau. Lahan pun tergolong bergambut yang agak masam.</p>
<p>Karakter istimewa yang stabil dan daya adaptasi tinggi tentu jadi idaman kolektor dan calon pekebun. saat disodori foto zainal mahang melalui surat elektronik. Ir Wijaya MS, penangkar buah di Cipaku, Bogor, pun mengamini peluang rambutan raksasa itu untuk dikebunkan asal bibit massal cepat tersedia. Sayang, hingga 2012 Zainal Abidin baru memperbanyak kurang dari 1.000 tanaman dengan teknik cangkok.</p>